import { prisma } from "@/lib/db";
import { requireHrOrAdmin } from "@/lib/permissions";
import { notFound, redirect } from "next/navigation";
import { AnalysisReport } from "@/components/hr/AnalysisReport";
import { PrintButton } from "@/components/hr/PrintButton";
import type { ParsedResume, ResumeScore } from "@/lib/resume-analyzer";

// Printable, downloadable score report. Open in a new tab and "Save as PDF".
export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const user = await requireHrOrAdmin();
  if (!user) redirect("/login");

  const { id } = await params;
  const applicant = await prisma.applicant.findUnique({
    where: { id },
    include: { job: true },
  });

  if (!applicant) notFound();

  const parsed = applicant.parsedData as unknown as ParsedResume;
  const score = applicant.remarks as unknown as ResumeScore;

  return (
    <div className="min-h-screen bg-[var(--arc-bg-primary)] py-8">
      <div className="max-w-5xl mx-auto px-6">
        <div className="flex items-center justify-between mb-6 print:hidden">
          <div>
            <p className="text-[10px] uppercase tracking-wider text-[var(--arc-text-tertiary)]">
              Candidate Evaluation Report
            </p>
            <h1 className="text-lg font-semibold">
              {applicant.name} · {applicant.job.title}
            </h1>
          </div>
          <PrintButton fileName={`${applicant.name.replace(/\s+/g, "_")}_${applicant.job.title.replace(/\s+/g, "_")}.pdf`} />
        </div>

        <div className="bg-[var(--arc-bg-primary)] print:bg-white print:text-black">
          <AnalysisReport
            applicantName={applicant.name}
            applicantEmail={applicant.email}
            jobTitle={applicant.job.title}
            jobDepartment={applicant.job.department}
            parsed={parsed}
            score={score}
            generatedAt={applicant.updatedAt}
            printMode
          />
        </div>

        <p className="text-[10px] text-[var(--arc-text-tertiary)] mt-8 text-center print:text-gray-500">
          Generated by ARC HR · Powered by Claude Opus 4.7 ·{" "}
          {new Date().toLocaleString()}
        </p>
      </div>
    </div>
  );
}
